# Site settings
name: Serenity's Website
email: cd2866@nyu.edu
author: serenity
url: 
resume_site: 
github: https://github.com/serenitydu/
baseurl: 
description: No description.
meta_description: No description.
motto: +1s
banner: +1s

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: serenitydu

# Build settings
markdown: kramdown


